In [1]:
import requests
import json
import pandas as pd
import numpy as np
import re
import math

response = requests.get('https://care.personcentredsoftware.com/mcm/api/v1/284748bf-6409-4367-887d-795f5458e954/organisationapi/Get/serviceusers?includeContacts=true').text;
response_info = json.loads(response)

In [2]:
# # returns the full name of the first service user
# userName = serviceUser['firstName'] + " " + serviceUser['lastName']

# # returns the room of the first service user
# userRoom = serviceUser['room']

# # returns an array with phone numbers of the first relationship of the first service user
# relationshipPhones = response_info[0]['serviceUsers'][0]['relationships'][0]['telephone']

# # returns true if the relationship is for an emergency contact
# isEmergencyContact = relationship['emergencyContact']

# # returns an array of the email of the first relationship of the first service user
# relationshipEmail = response_info[0]['serviceUsers'][0]['relationships'][0]['email']

In [3]:
firstNames = []
lastNames = []
userRooms = []
telephones = []
email = []
notes = []
emergencyName=[]

def getUserInformation(): 
    for serviceUser in response_info[0]['serviceUsers']:
        for relationship in serviceUser['relationships']:
            firstName = serviceUser['firstName']
            lastName = serviceUser['lastName']
            userRoom = serviceUser['room']
            relationshipPhones = relationship['telephone']
            relationshipEmail = relationship['email']
            relationshipNotes = relationship['notes']
            relationshipName=relationship['personName']
            
            firstNames.append(firstName)
            lastNames.append(lastName)
            userRooms.append(userRoom)
            telephones.append(relationshipPhones)
            email.append(relationshipEmail) 
            notes.append(relationshipNotes)
            emergencyName.append(relationshipName)

In [4]:
getUserInformation()

In [5]:
flex_df = pd.DataFrame(columns=['Resident Last Name','Resident First Name',
                                'Resident Room','Units','Contacts Last Name','Contacts First Name',
                                'Phones','Notes','Contacts Home Phone','Contacts Mobile Phone','Contacts Email'])

In [6]:
flex_df['Resident First Name'] = firstNames
flex_df['Resident Last Name'] = lastNames
flex_df['Resident Room'] = userRooms
flex_df['Phones'] = telephones
flex_df['Contacts First Name'] = emergencyName
flex_df['Contacts Email'] = email
flex_df['Notes'] = notes

In [7]:
def telephoneChecker():
   
    phone_data1 = []
    phone_data2 = []
    mobile_list = []
    landline_list = []

    for index, row in flex_df.iterrows():
        if len(row['Phones']) > 1: 
            phone_data1.append(row['Phones'][0])
            phone_data2.append(row['Phones'][1])      
        elif len(row['Phones']) == 1:

            if len(row['Phones'][0]) > 0:
                phone_data1.append(row['Phones'][0])
                phone_data2.append(0) 
            else:
                phone_data1.append(0)
                phone_data2.append(0)

    flex_df["Phone1"] = phone_data1
    flex_df["Phone2"] = phone_data2

    del flex_df['Phones']
    
    for index, row in flex_df.iterrows():
        # 0,0
        if row['Phone1'] == 0:
            mobile_list.append("")
            landline_list.append("")
        # Mobile + ?
        elif re.search("^07", row['Phone1']) is not None:
            if row['Phone2'] == 0:
                # Mobile + 0
                mobile_list.append(row['Phone1'])
                landline_list.append("")
            # Mobile + Landline (or Mobile2)
            else:
                mobile_list.append(row['Phone1'])
                landline_list.append(row['Phone2'])  
        else:
            # Landline + ?
            if row['Phone2'] == 0:
                # Landline + 0
                landline_list.append(row['Phone1'])
                mobile_list.append("")
            # Landline + Mobile (or Landline2)
            else:
                landline_list.append(row['Phone1'])
                mobile_list.append(row['Phone2'])
    
    flex_df['Contacts Mobile Phone'] = mobile_list
    flex_df['Contacts Home Phone'] = landline_list
    del flex_df['Phone1']
    del flex_df['Phone2']

In [8]:
def emailChecker():
    
    email_list=[]

    for email in flex_df['Contacts Email']:
        if len(email[0])==0:
            email_list.append("")
        else:
            email_list.append(email[0])
            
    del flex_df['Contacts Email']
    flex_df['Contacts Email']= email_list

In [9]:
telephoneChecker()
emailChecker()

In [11]:
flex_df

,Resident Last Name,Resident First Name,Resident Room,Units,Contacts Last Name,Contacts First Name,Notes,Contacts Home Phone,Contacts Mobile Phone,Contacts Email
0,Oak,Joyce,25,NaN,NaN,Mrs Nicola Papp,PR:T,01291 672455,07885989677,
1,Oak,Joyce,25,NaN,NaN,Malpas Brook Health Centre,None,01633 855808,,
2,Oak,Joyce,25,NaN,NaN,Mrs Yvonne Wyatt,None,01633 661130,07810805054,derekandyvonnewyattskittlefish2512@gmail.com
3,Pring,Judith,6,NaN,NaN,Ms Tina Compton,PR:T,01633 258248,07708 044 760,
4,Pring,Judith,6,NaN,NaN,Malpas Brook Health Centre,None,01633 855808,,
...,...,...,...,...,...,...,...,...,...,...
99,Fortey,Margaret,18,NaN,NaN,Mr Stuart Fortey,PR:T,,07760 415 766,
100,Fortey,Margaret,18,NaN,NaN,Heather Davies,None,,07787438343,
101,Fortey,Margaret,18,NaN,NaN,Mr Gareth Fortey,None,,07508 750 421,
102,Lewis,Marian,12,NaN,NaN,Bryngwyn Surgery,None,01633 263463,,
103,Lewis,Marian,12,NaN,NaN,Mrs Angela Aitken,PR:E,,07876 695 907,angela.aitken13@gmail.com

In [14]:
def notesChecker():
    
    PR_T = "PR:T"
    PR_V = "PR:V"
    PR_E = "PR:E"
    PR_N = "PR:N"
    
    notes_list=[]
    
    for index, row in flex_df.iterrows():
        # Check Notes that contain None
        if row['Notes'] is None:
            row['Notes'] = ""
#       PR:T
        elif PR_T in row['Notes']:
            row['Notes'] = PR_T
#       PR:V
        elif PR_V in row['Notes']:
            row['Notes'] = PR_V        
#       PR:E
        elif PR_E in row['Notes']:
            row['Notes'] = PR_E
#       PR:N
        elif PR_N in row['Notes']:
            row['Notes'] = "PR_N"            
        else:
            row['Notes'] = ""
notesChecker()

In [15]:
flex_df.tail(50)

,Resident Last Name,Resident First Name,Resident Room,Units,Contacts Last Name,Contacts First Name,Notes,Contacts Home Phone,Contacts Mobile Phone,Contacts Email
54,Kerr,Maureen,22,NaN,NaN,Mrs Lynn Kerr,,,,
55,Kerr,Maureen,22,NaN,NaN,Ms Helen Collins,,,07789205872,h.collins58@ntlworld.com
56,Kerr,Maureen,22,NaN,NaN,Mr Andrew Kerr,PR:T,,07714103413,
57,Kerr,Maureen,22,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
58,Breen,Bridget,14,NaN,NaN,Bryngwyn Surgery,,01633 263463,,
59,Breen,Bridget,14,NaN,NaN,Mrs Karen Breen,PR:E,,07783042005,
60,Breen,Bridget,14,NaN,NaN,Mr Terrance Breen,,,07757358342,
61,Breen,Bridget,14,NaN,NaN,Ms Katie (Breen) Daughter in London,,,07547 478 255,
62,Breen,Bridget,14,NaN,NaN,Mr Michael Breen,,,07976124931,
63,Breen,Bridget,14,NaN,NaN,Mr Peter Breen,,,07795 207 252,
64,Breen,Mick,24,NaN,NaN,Mr Terrance Breen,,,07757358342,
65,Breen,Mick,24,NaN,NaN,Bryngwyn Surgery,,01633 263463,,
66,Breen,Mick,24,NaN,NaN,Ms Katie (Breen) Daughter in London,,,07547 478 255,
67,Breen,Mick,24,NaN,NaN,Mrs Karen Breen,PR:T,,07783042005,
68,Breen,Mick,24,NaN,NaN,Mr Michael Breen,PR:T,,07976124931,
69,Breen,Mick,24,NaN,NaN,Mr Peter Breen,,,07795 207 252,
70,Jones,June,17,NaN,NaN,Ms Denise Wilkings,,,07817 048 052,
71,Jones,June,17,NaN,NaN,Mrs Jeanette Lovell,PR:E,,07920 052 814,slovell1965@gmail.com
72,Short,John,16,NaN,NaN,Mrs Mary Ford,,01633 264178,,
73,Short,John,16,NaN,NaN,Mr Steve Short,PR:E,,07570 273 542,steveshort06@gmail.com
74,Short,John,16,NaN,NaN,Mr Gary Short,,01633 673887,07525 706 585,
75,Short,John,16,NaN,NaN,Park Surgery,,01633 277442,,
76,May,John,10,NaN,NaN,Mr Lyndon May,,,07731 163 078,
77,May,John,10,NaN,NaN,Mrs Catherine Jones,,,07513 101 635,kljones82@live.co.uk
78,May,John,10,NaN,NaN,Ms Vicky May,PR:E,,07773 465 585,
79,May,John,10,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
80,Maidment,Elsie,13,NaN,NaN,Mrs Yvonne Challingsworth,PR:E,,07875 031 607,yvonne270609@gmail.com
81,Maidment,Elsie,13,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
82,Maidment,Elsie,13,NaN,NaN,Mr Phil Howells,,,07717 159 567,
83,Maidment,Elsie,13,NaN,NaN,Mr Rugby Surgery,,01633 258564,,
84,Maidment,Elsie,13,NaN,NaN,Mrs Lesley Howells,,,07716 516 055,phil@linstar.co.uk
85,James,Keith,21,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
86,James,Keith,21,NaN,NaN,Paul Grifiths,,,07721080332,
87,James,Keith,21,NaN,NaN,Sue Griffiths,PR:T,01633 897151,07721080332,
88,James,Keith,21,NaN,NaN,Mr Owen Griffiths,,,07952785875,
89,Graham,Marjorie,27,NaN,NaN,Mrs Bronwen Graham,,01633 227782,07940400088,
90,Graham,Marjorie,27,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
91,Graham,Marjorie,27,NaN,NaN,Mr Doug Graham,PR:T,01633 782933,07960020532,
92,Evans,Margery,2,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
93,Evans,Margery,2,NaN,NaN,Carys Nelkon,,,07776345896,
94,Evans,Margery,2,NaN,NaN,Mr Phillip Nelkon,,,07785737530,
95,Evans,Margery,2,NaN,NaN,Mrs Julie Nelkon,,0208 8869050,07506076237,
96,Walker,Michelle,4,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
97,Walker,Michelle,4,NaN,NaN,Miss Lisa Walker,PR:T,,07946 830 977,
98,Fortey,Margaret,18,NaN,NaN,Malpas Brook Health Centre,,01633 855808,,
99,Fortey,Margaret,18,NaN,NaN,Mr Stuart Fortey,PR:T,,07760 415 766,
100,Fortey,Margaret,18,NaN,NaN,Heather Davies,,,07787438343,
101,Fortey,Margaret,18,NaN,NaN,Mr Gareth Fortey,,,07508 750 421,
102,Lewis,Marian,12,NaN,NaN,Bryngwyn Surgery,,01633 263463,,
103,Lewis,Marian,12,NaN,NaN,Mrs Angela Aitken,PR:E,,07876 695 907,angela.aitken13@gmail.com

In [ ]:
flex_df.to_csv(r'flex.csv', header=True, index=False)